services:
  # dashboard:
  #   build:
  #     context: ./dashboard
  #   command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0
  #   environment:
  #     - PYTHONPATH=/app
  #     - DB_URL=${DB_URL}
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - redis

  # celery-worker:
  #   build:
  #     context: .
  #     dockerfile: scheduler/Dockerfile
  #   command: celery -A scheduler.app.celery worker --loglevel=INFO
  #   volumes:
  #     - ./database:/app/database
  #   depends_on:
  #     - redis

  # celery-beat:
  #   build:
  #     context: .
  #     dockerfile: scheduler/Dockerfile
  #   command: celery -A scheduler.app.celery beat --loglevel=INFO --schedule=/tmp/celerybeat-schedule
  #   environment:
  #     - PYTHONPATH=/app
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_BACKEND_URL=redis://redis:6379/1
  #     - DB_URL=${DB_URL}
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge