services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    environment:
      - PYTHONPATH=/app
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8501:8501"
    depends_on:
      - redis
      - postgres

  celery-scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: celery -A scheduler.celery_app:celery_app worker -Q scheduler -n scheduler@%h -l INFO
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres

  celery-executor:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: celery -A scheduler.celery_app:celery_app worker -Q executor -n executor@%h -l INFO
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
    depends_on:
      - redis
      - postgres

  celery-beat:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: celery -A scheduler.celery_app:celery_app beat -l INFO --schedule=/tmp/celerybeat-schedule
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
      - beat-state:/tmp
    depends_on:
      - redis
      - postgres

volumes:
  beat-state:
  postgres-data:
