services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    command: streamlit run dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - redis

  celery-scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: celery -A scheduler.celery_app:celery_app worker -Q scheduler -n scheduler@%h -l INFO
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-executor:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: celery -A scheduler.celery_app:celery_app worker -Q executor -n executor@%h -l INFO
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    command: celery -A scheduler.celery_app:celery_app beat -l INFO --schedule=/tmp/celerybeat-schedule
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
      - beat-state:/tmp
    depends_on:
      - redis

volumes:
  beat-state:
