"""add planer enabled field

Revision ID: 814095137c8c
Revises: 8f55354f5127
Create Date: 2025-08-28 16:20:27.195848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814095137c8c'
down_revision: Union[str, Sequence[str], None] = '8f55354f5127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_settings', sa.Column('planer_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_settings', 'planer_enabled')
    # ### end Alembic commands ###
