"""init

Revision ID: 8f55354f5127
Revises: 
Create Date: 2025-08-25 13:15:04.453909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f55354f5127'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scripts', sa.JSON(), nullable=False),
    sa.Column('parallel_limit', sa.Integer(), server_default='1', nullable=False),
    sa.Column('create_batch', sa.Integer(), server_default='1', nullable=False),
    sa.Column('step_timeout', sa.Integer(), server_default='3600', nullable=False),
    sa.Column('retry_limit', sa.Integer(), server_default='3', nullable=False),
    sa.Column('backoff_initial', sa.Integer(), server_default='60', nullable=False),
    sa.Column('backoff_factor', sa.Float(), server_default='2.0', nullable=False),
    sa.Column('backoff_max', sa.Integer(), server_default='3600', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_settings_name'), 'task_settings', ['name'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('step_status', sa.Enum('Ожидание', 'В работе', 'Ошибка', 'Успешно', name='step_status', native_enum=False), server_default='Ожидание', nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('step_started_at', sa.DateTime(), nullable=True),
    sa.Column('step_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('card_number', sa.String(length=30), nullable=True),
    sa.Column('card_date', sa.String(length=10), nullable=True),
    sa.Column('card_cvv', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_locked_by'), 'tasks', ['locked_by'], unique=False)
    op.create_index(op.f('ix_tasks_locked_until'), 'tasks', ['locked_until'], unique=False)
    op.create_index(op.f('ix_tasks_next_attempt_at'), 'tasks', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_tasks_step_status'), 'tasks', ['step_status'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_tasks_step_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_next_attempt_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_locked_until'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_locked_by'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_task_settings_name'), table_name='task_settings')
    op.drop_table('task_settings')
    # ### end Alembic commands ###
